### Cash deposit check
POST http://localhost:8080/api/deposit
Content-Type: application/json

{
  "user_id": 1,
  "amount": 100.00
}

### Cash withdraw check
POST http://localhost:8080/api/withdraw
Content-Type: application/json

{
"user_id": 1,
"amount": 50.00
}
